# Dependencies
markdown:         redcarpet
extensions:       ["footnotes", "superscript"]	

highlighter:      pygments
gems:
- jekyll-gist
- jekyll-paginate

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:           A San Franciscan
tagline:          'Un poquito de todo'
description:      'Un poquito de todo'
url:              http://chema.sanfranciscan.org
baseurl:          /

author:
  name:           'Chema Hernández Gil'
  url:            https://twitter.com/elsanfranciscan

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/chema.github.io
