# Dependencies
markdown:         kramdown
redcarpet:
  extensions:     ["footnotes", "superscript"]

highlighter:      rouge
plugins:
- jekyll-gist
- jekyll-paginate

# Permalinks
permalink:        pretty
excerpt_separator:  <!--more-->
# relative_permalinks: true

# Setup
title:            The San Franciscan
tagline:          'Un poquito de todo'
description:      'Un poquito de todo'
url:              https://sanfranciscan.org/
baseurl:          /
twitter_username: elsanfranciscan

author:
  name:           'Chema Hernández Gil'
  url:            https://twitter.com/elsanfranciscan

paginate:         4

# Custom vars
version:          2.1.0

# github:
#   repo:           https://github.com/chema/chema.github.io

# piwik:
#  base_url: sanfranciscan.org
#  site_id: 1
